"""
training/scripts/build_vector_db.py
======================================
Builds the FAISS vector index from the prepared RAG corpus.

Steps:
1. Load rag_corpus.jsonl (generated by prepare_dataset.py)
2. Embed each chunk using sentence-transformers (multilingual MiniLM)
3. Store embeddings in FAISS flat L2 index
4. Save index + metadata to disk

Usage:
  python training/scripts/build_vector_db.py \
    --corpus_file backend/data/rag_corpus.jsonl \
    --output_dir  backend/models/saved/faiss_index

Requirements:
  pip install faiss-cpu sentence-transformers
  (Use faiss-gpu if you have a CUDA-enabled GPU)
"""
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["OMP_NUM_THREADS"] = "1"

import argparse
import json
import logging
import sys
from pathlib import Path

import numpy as np
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger(__name__)

EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
EMBEDDING_DIM   = 384   # MiniLM-L12-v2 output dimension
BATCH_SIZE      = 16


def load_corpus(corpus_file: Path) -> list[dict]:
    """Load JSONL corpus file."""
    chunks = []
    with open(corpus_file, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    chunks.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    logger.info(f"Loaded {len(chunks)} chunks from {corpus_file}")
    return chunks


def embed_chunks(
    chunks: list[dict],
    model_name: str = EMBEDDING_MODEL,
    batch_size: int = BATCH_SIZE,
) -> np.ndarray:
    """
    Embed all text chunks using sentence-transformers.
    Returns numpy array of shape [N, embedding_dim].
    """
    from sentence_transformers import SentenceTransformer

    logger.info(f"Loading embedding model: {model_name}")
    embedder = SentenceTransformer(model_name)

    texts = [c["text"] for c in chunks]
    logger.info(f"Embedding {len(texts)} chunks (batch_size={batch_size}) …")

    embeddings = embedder.encode(
        texts,
        batch_size=batch_size,
        show_progress_bar=True,
        normalize_embeddings=True,   # L2 normalize for cosine similarity via dot product
        convert_to_numpy=True,
    )

    logger.info(f"Embeddings shape: {embeddings.shape}")
    return embeddings.astype(np.float32)


def build_faiss_index(embeddings: np.ndarray) -> "faiss.Index":
    """
    Build a FAISS flat inner-product index.
    With L2-normalized embeddings, inner product = cosine similarity.
    """
    import faiss

    dim = embeddings.shape[1]
    logger.info(f"Building FAISS IndexFlatIP (dim={dim}, n={len(embeddings)}) …")

    # For large corpora (>100k chunks), consider IndexIVFFlat for speed:
    # quantizer = faiss.IndexFlatIP(dim)
    # index = faiss.IndexIVFFlat(quantizer, dim, 100, faiss.METRIC_INNER_PRODUCT)
    # index.train(embeddings)

    index = faiss.IndexFlatIP(dim)   # Exact search, good for <500k chunks
    index.add(embeddings)

    logger.info(f"FAISS index built: {index.ntotal} vectors")
    return index


def save_index(
    index: "faiss.Index",
    chunks: list[dict],
    output_dir: Path,
) -> None:
    """Save FAISS index + chunk metadata to disk."""
    import faiss

    output_dir.mkdir(parents=True, exist_ok=True)

    index_path = output_dir / "legal_index.faiss"
    meta_path  = output_dir / "chunk_metadata.json"

    faiss.write_index(index, str(index_path))
    logger.info(f"✅  FAISS index saved → {index_path}")

    # Save only essential metadata (strip large fields to save space)
    metadata = [
        {
            "text":    c.get("text", "")[:500],  # truncate to 500 chars
            "section": c.get("section", ""),
            "title":   c.get("title", ""),
            "act":     c.get("act", ""),
            "source":  c.get("source", ""),
        }
        for c in chunks
    ]

    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)
    logger.info(f"✅  Metadata saved     → {meta_path}")


def verify_index(index: "faiss.Index", embedder_model: str, query: str) -> None:
    """Quick sanity check: search index with a test query."""
    from sentence_transformers import SentenceTransformer
    embedder = SentenceTransformer(embedder_model)
    vec = embedder.encode([query], normalize_embeddings=True).astype(np.float32)
    distances, indices = index.search(vec, 3)
    logger.info(f"Test query: '{query}'")
    logger.info(f"  Top-3 indices: {indices[0]}, scores: {distances[0]}")


def main():
    parser = argparse.ArgumentParser(description="Build FAISS vector DB for Legal AI RAG")
    parser.add_argument("--corpus_file", type=str, default="backend/data/rag_corpus.jsonl")
    parser.add_argument("--output_dir",  type=str, default="backend/models/saved/faiss_index")
    parser.add_argument("--model",       type=str, default=EMBEDDING_MODEL)
    args = parser.parse_args()

    corpus_file = Path(args.corpus_file)
    output_dir  = Path(args.output_dir)

    if not corpus_file.exists():
        logger.error(f"Corpus file not found: {corpus_file}")
        logger.error("Run prepare_dataset.py first.")
        sys.exit(1)

    logger.info("=" * 60)
    logger.info("⚖️  Legal AI — Building FAISS Vector Index")
    logger.info("=" * 60)

    # 1. Load corpus
    chunks = load_corpus(corpus_file)
    if not chunks:
        logger.error("Empty corpus. Add legal PDFs to training/data_prep/raw/ and re-run prepare_dataset.py")
        sys.exit(1)

    # 2. Embed
    embeddings = embed_chunks(chunks, model_name=args.model)

    # 3. Build FAISS index
    index = build_faiss_index(embeddings)

    # 4. Save
    save_index(index, chunks, output_dir)

    # 5. Quick verification
    verify_index(index, args.model, "assault causing hurt voluntarily")

    logger.info("\n✅  Vector DB build complete!")
    logger.info(f"   Index: {output_dir}/legal_index.faiss")
    logger.info(f"   Meta:  {output_dir}/chunk_metadata.json")
    logger.info(f"   Total vectors: {index.ntotal}")


if __name__ == "__main__":
    main()
